# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'pockettrader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pockettrader
  pod 'Firebase/Core'

  target 'pockettraderTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'pockettrader-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pockettrader-tvOS

  target 'pockettrader-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
